import {
  Box,
  Typography,
  Paper,
  Button,
  Divider,
  Grid,
  List,
  ListItem,
  ListItemText,
  useTheme
} from '@mui/material';

export default function TermsPage({ onBack }) {
  const theme = useTheme();
  const isDarkMode = theme.palette.mode === 'dark';

  const sections = [
    {
      icon: '📋',
      title: '1. Acceptance of Terms',
      content: `By accessing or using MailGenie ("the Application"), you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, you may not use the Application. MailGenie is provided as an open-source developer tool and is subject to change without notice.`
    },
    {
      icon: '⚙️',
      title: '2. Description of Service',
      content: `MailGenie is an AI-powered email reply generator that integrates with Gmail via a Chrome Extension and provides a standalone web interface. The Application interfaces with third-party Large Language Model (LLM) providers including Groq, OpenAI, Google Gemini, and Anthropic Claude to generate email reply drafts based on user-supplied context.`
    },
    {
      icon: '🔑',
      title: '3. API Keys and Credentials',
      content: `You are solely responsible for any API keys, credentials, or access tokens you configure within MailGenie. MailGenie stores these credentials locally in your browser storage (Chrome Extension) or in a local configuration file (Spring Boot backend). We do not transmit or store your API keys on any external server. Misuse of API keys violates the respective provider's terms of service and is your sole responsibility.`
    },
    {
      icon: '🤖',
      title: '4. AI-Generated Content Disclaimer',
      content: `All email drafts generated by MailGenie are produced by third-party AI models and may be inaccurate, incomplete, or inappropriate. You are fully responsible for reviewing, editing, and approving any AI-generated content before sending it. MailGenie makes no warranty as to the accuracy, suitability, or professional quality of generated replies.`
    },
    {
      icon: '📧',
      title: '5. Email Content and Privacy',
      content: `When you paste email content into MailGenie, that content is transmitted to your configured LLM provider's API for processing. By using MailGenie, you acknowledge that email content you input may be processed by third-party AI services subject to their respective privacy policies. Do not submit confidential, sensitive, or personally identifiable information that you are not authorized to share.`
    },
    {
      icon: '🔓',
      title: '6. Open-Source License',
      content: `MailGenie is distributed as open-source software under the MIT License. You are free to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software, subject to the conditions of the MIT License included in the repository. The open-source nature of MailGenie means contributions are welcome via pull requests on the GitHub repository.`
    },
    {
      icon: '⚠️',
      title: '7. Limitation of Liability',
      content: `MailGenie is provided "as is" without warranty of any kind, express or implied. In no event shall the MailGenie contributors or maintainers be liable for any indirect, incidental, special, exemplary, or consequential damages arising out of the use or inability to use the Application, even if advised of the possibility of such damages.`
    },
    {
      icon: '🔄',
      title: '8. Changes to Terms',
      content: `We reserve the right to modify these Terms of Use at any time. Changes will be reflected in the repository's documentation. Continued use of MailGenie after any modifications constitutes your acceptance of the new terms. We encourage you to review these terms periodically.`
    }
  ];

  return (
    <Box sx={{ py: 2 }}>
      {/* Header */}
      <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 2 }}>
        <Box>
          <Typography variant="h3" component="h1" gutterBottom className="app-title">
            📜 Terms of Use
          </Typography>
          <Typography variant="body1" sx={{ color: 'text.secondary' }}>
            Last updated: July 2026 · Please read these terms carefully before using MailGenie.
          </Typography>
        </Box>
        <Button
          variant="outlined"
          onClick={onBack}
          sx={{ borderRadius: '12px', py: 1, px: 2, textTransform: 'none', fontWeight: 600, whiteSpace: 'nowrap' }}
        >
          ← Back to Generator
        </Button>
      </Box>

      {/* Intro Banner */}
      <Paper
        className="glass-card"
        sx={{
          p: 3,
          mb: 5,
          background: isDarkMode
            ? 'linear-gradient(135deg, rgba(99,102,241,0.12) 0%, rgba(192,132,252,0.08) 100%)'
            : 'linear-gradient(135deg, rgba(99,102,241,0.06) 0%, rgba(192,132,252,0.04) 100%)',
          borderLeft: '4px solid #6366f1'
        }}
      >
        <Typography variant="body1" sx={{ lineHeight: 1.8, color: 'text.secondary' }}>
          These Terms of Use govern your use of the MailGenie application, including the Chrome Extension, the standalone React web interface, and the Spring Boot API backend. By using any part of MailGenie, you agree to these terms.
        </Typography>
      </Paper>

      {/* Sections Grid */}
      <Grid container spacing={3} sx={{ mb: 5 }}>
        {sections.map((section) => (
          <Grid item xs={12} key={section.title}>
            <Paper
              className="glass-card"
              sx={{ p: 4 }}
            >
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 2 }}>
                <Typography variant="h5" sx={{ lineHeight: 1 }}>{section.icon}</Typography>
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  {section.title}
                </Typography>
              </Box>
              <Divider sx={{ mb: 2.5, borderColor: isDarkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)' }} />
              <Typography variant="body2" sx={{ color: 'text.secondary', lineHeight: 1.85 }}>
                {section.content}
              </Typography>
            </Paper>
          </Grid>
        ))}
      </Grid>

      {/* Quick Summary */}
      <Paper className="glass-card" sx={{ p: 4, mb: 4 }}>
        <Typography variant="h6" sx={{ fontWeight: 700, mb: 2 }}>
          ✅ Summary of Key Points
        </Typography>
        <Divider sx={{ mb: 3, borderColor: isDarkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)' }} />
        <List sx={{ p: 0 }}>
          {[
            'MailGenie is open-source software — free to use, fork, and contribute to.',
            'Your API keys are stored locally and never transmitted to MailGenie servers.',
            'AI-generated content must be reviewed before sending — we are not liable for its accuracy.',
            'Email content you paste is sent to your chosen AI provider for processing.',
            'MailGenie is provided "as is" with no guarantees of uptime or suitability.',
          ].map((point, i) => (
            <ListItem key={i} sx={{ py: 0.8, px: 0 }}>
              <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: 'primary.main', mr: 2, flexShrink: 0 }} />
              <ListItemText
                primary={point}
                primaryTypographyProps={{ variant: 'body2', color: 'text.secondary', lineHeight: 1.6 }}
              />
            </ListItem>
          ))}
        </List>
      </Paper>

      {/* Footer CTA */}
      <Box sx={{ textAlign: 'center', py: 3 }}>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Have questions about these terms? Reach out to the MailGenie team.
        </Typography>
        <Button
          variant="contained"
          className="gradient-btn"
          onClick={() => onBack && onBack('contact')}
          sx={{ mr: 2 }}
        >
          Contact Us
        </Button>
        <Button
          variant="outlined"
          onClick={onBack}
          sx={{ borderRadius: '12px', textTransform: 'none', fontWeight: 600 }}
        >
          Back to Generator
        </Button>
      </Box>
    </Box>
  );
}
